import * as path from "path";

import { ReadmeData } from "./interface";

export function buildReadme(data: ReadmeData): string {
    return `# ${path.basename(data.rootPath)}

## 🏷 Version: ${data.version}
## 📜 License: ${data.license}

## 📖 Description
This project was automatically generated by the **README Generator** extension.

## ⚙️ Prod stack technologies
${data.techs.join(", ") || "Not found"}

## ⚙️ Dev stack technologies
${data.devDep.join(", ") || "Not found"}

## 📜 Scripts available
${data.scripts.length ? data.scripts.map(s => `- \`${s}\``).join("\n") : "No definidos"}

## 🌐 Deployment & Infrastructure
${data.infraTools.join(", ") || "Not found"}

## Clone repository
\`\`\`bash
git clone ${data.repo !== "No repository found" ? data.repo : ""}
\`\`\`

## 📂 Project structure
\`\`\`
${data.structure}
\`\`\`
`;
}
