export const DEP_TO_TECH: { [key: string]: string } = {
    "react": "React",
    "react-dom": "React DOM",
    "vue": "Vue.js",
    "angular": "Angular",
    "svelte": "Svelte",
    "next": "Next.js",
    "nuxt": "Nuxt.js",
    "gatsby": "Gatsby",
    "typescript": "TypeScript",
    "express": "Express",
    "koa": "Koa",
    "fastify": "Fastify",
    "nestjs": "NestJS",
    "hapi": "Hapi",
    "pg": "PostgreSQL",
    "mysql": "MySQL",
    "mongodb": "MongoDB",
    "sqlite3": "SQLite",
    "typeorm": "TypeORM",
    "prisma": "Prisma",
    "babel": "Babel",
    "webpack": "Webpack",
    "vite": "Vite",
    "rollup": "Rollup",
    "jest": "Jest",
    "mocha": "Mocha",
    "chai": "Chai",
    "eslint": "ESLint",
    "prettier": "Prettier",
    "dotenv": "dotenv",
    "axios": "Axios",
    "lodash": "Lodash",
    "cors": "CORS",
    "body-parser": "body-parser"
};
